import type { PhoneCountry } from "../types.js";

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { code: "AF", name: "Afghanistan", dialCode: "93", flag: "🇦🇫" },
  { code: "AL", name: "Albania", dialCode: "355", flag: "🇦🇱" },
  { code: "DZ", name: "Algeria", dialCode: "213", flag: "🇩🇿" },
  { code: "AS", name: "American Samoa", dialCode: "1684", flag: "🇦🇸" },
  { code: "AD", name: "Andorra", dialCode: "376", flag: "🇦🇩" },
  { code: "AO", name: "Angola", dialCode: "244", flag: "🇦🇴" },
  { code: "AI", name: "Anguilla", dialCode: "1264", flag: "🇦🇮" },
  { code: "AG", name: "Antigua and Barbuda", dialCode: "1268", flag: "🇦🇬" },
  { code: "AR", name: "Argentina", dialCode: "54", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", dialCode: "374", flag: "🇦🇲" },
  { code: "AW", name: "Aruba", dialCode: "297", flag: "🇦🇼" },
  { code: "AU", name: "Australia", dialCode: "61", flag: "🇦🇺" },
  { code: "AT", name: "Austria", dialCode: "43", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", dialCode: "994", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", dialCode: "1242", flag: "🇧🇸" },
  { code: "BH", name: "Bahrain", dialCode: "973", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", dialCode: "880", flag: "🇧🇩" },
  { code: "BB", name: "Barbados", dialCode: "1246", flag: "🇧🇧" },
  { code: "BY", name: "Belarus", dialCode: "375", flag: "🇧🇾" },
  { code: "BE", name: "Belgium", dialCode: "32", flag: "🇧🇪" },
  { code: "BZ", name: "Belize", dialCode: "501", flag: "🇧🇿" },
  { code: "BJ", name: "Benin", dialCode: "229", flag: "🇧🇯" },
  { code: "BM", name: "Bermuda", dialCode: "1441", flag: "🇧🇲" },
  { code: "BT", name: "Bhutan", dialCode: "975", flag: "🇧🇹" },
  { code: "BO", name: "Bolivia", dialCode: "591", flag: "🇧🇴" },
  { code: "BA", name: "Bosnia and Herzegovina", dialCode: "387", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", dialCode: "267", flag: "🇧🇼" },
  { code: "BR", name: "Brazil", dialCode: "55", flag: "🇧🇷" },
  { code: "VG", name: "British Virgin Islands", dialCode: "1284", flag: "🇻🇬" },
  { code: "BN", name: "Brunei", dialCode: "673", flag: "🇧🇳" },
  { code: "BG", name: "Bulgaria", dialCode: "359", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", dialCode: "226", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", dialCode: "257", flag: "🇧🇮" },
  { code: "KH", name: "Cambodia", dialCode: "855", flag: "🇰🇭" },
  { code: "CM", name: "Cameroon", dialCode: "237", flag: "🇨🇲" },
  { code: "CA", name: "Canada", dialCode: "1", flag: "🇨🇦" },
  { code: "CV", name: "Cape Verde", dialCode: "238", flag: "🇨🇻" },
  { code: "KY", name: "Cayman Islands", dialCode: "1345", flag: "🇰🇾" },
  { code: "CF", name: "Central African Republic", dialCode: "236", flag: "🇨🇫" },
  { code: "TD", name: "Chad", dialCode: "235", flag: "🇹🇩" },
  { code: "CL", name: "Chile", dialCode: "56", flag: "🇨🇱" },
  { code: "CN", name: "China", dialCode: "86", flag: "🇨🇳" },
  { code: "CO", name: "Colombia", dialCode: "57", flag: "🇨🇴" },
  { code: "KM", name: "Comoros", dialCode: "269", flag: "🇰🇲" },
  { code: "CG", name: "Congo", dialCode: "242", flag: "🇨🇬" },
  { code: "CR", name: "Costa Rica", dialCode: "506", flag: "🇨🇷" },
  { code: "HR", name: "Croatia", dialCode: "385", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", dialCode: "53", flag: "🇨🇺" },
  { code: "CY", name: "Cyprus", dialCode: "357", flag: "🇨🇾" },
  { code: "CZ", name: "Czechia", dialCode: "420", flag: "🇨🇿" },
  { code: "DK", name: "Denmark", dialCode: "45", flag: "🇩🇰" },
  { code: "DO", name: "Dominican Republic", dialCode: "1809", flag: "🇩🇴" },
  { code: "EC", name: "Ecuador", dialCode: "593", flag: "🇪🇨" },
  { code: "EG", name: "Egypt", dialCode: "20", flag: "🇪🇬" },
  { code: "EE", name: "Estonia", dialCode: "372", flag: "🇪🇪" },
  { code: "FI", name: "Finland", dialCode: "358", flag: "🇫🇮" },
  { code: "FR", name: "France", dialCode: "33", flag: "🇫🇷" },
  { code: "DE", name: "Germany", dialCode: "49", flag: "🇩🇪" },
  { code: "GR", name: "Greece", dialCode: "30", flag: "🇬🇷" },
  { code: "HK", name: "Hong Kong", dialCode: "852", flag: "🇭🇰" },
  { code: "HU", name: "Hungary", dialCode: "36", flag: "🇭🇺" },
  { code: "IS", name: "Iceland", dialCode: "354", flag: "🇮🇸" },
  { code: "IN", name: "India", dialCode: "91", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", dialCode: "62", flag: "🇮🇩" },
  { code: "IR", name: "Iran", dialCode: "98", flag: "🇮🇷" },
  { code: "IE", name: "Ireland", dialCode: "353", flag: "🇮🇪" },
  { code: "IL", name: "Israel", dialCode: "972", flag: "🇮🇱" },
  { code: "IT", name: "Italy", dialCode: "39", flag: "🇮🇹" },
  { code: "JP", name: "Japan", dialCode: "81", flag: "🇯🇵" },
  { code: "KE", name: "Kenya", dialCode: "254", flag: "🇰🇪" },
  { code: "KR", name: "South Korea", dialCode: "82", flag: "🇰🇷" },
  { code: "MX", name: "Mexico", dialCode: "52", flag: "🇲🇽" },
  { code: "NL", name: "Netherlands", dialCode: "31", flag: "🇳🇱" },
  { code: "NZ", name: "New Zealand", dialCode: "64", flag: "🇳🇿" },
  { code: "NO", name: "Norway", dialCode: "47", flag: "🇳🇴" },
  { code: "PK", name: "Pakistan", dialCode: "92", flag: "🇵🇰" },
  { code: "PL", name: "Poland", dialCode: "48", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", dialCode: "351", flag: "🇵🇹" },
  { code: "RO", name: "Romania", dialCode: "40", flag: "🇷🇴" },
  { code: "RU", name: "Russia", dialCode: "7", flag: "🇷🇺" },
  { code: "SA", name: "Saudi Arabia", dialCode: "966", flag: "🇸🇦" },
  { code: "SG", name: "Singapore", dialCode: "65", flag: "🇸🇬" },
  { code: "ZA", name: "South Africa", dialCode: "27", flag: "🇿🇦" },
  { code: "ES", name: "Spain", dialCode: "34", flag: "🇪🇸" },
  { code: "SE", name: "Sweden", dialCode: "46", flag: "🇸🇪" },
  { code: "CH", name: "Switzerland", dialCode: "41", flag: "🇨🇭" },
  { code: "TR", name: "Turkey", dialCode: "90", flag: "🇹🇷" },
  { code: "UA", name: "Ukraine", dialCode: "380", flag: "🇺🇦" },
  { code: "AE", name: "United Arab Emirates", dialCode: "971", flag: "🇦🇪" },
  { code: "GB", name: "United Kingdom", dialCode: "44", flag: "🇬🇧" },
  { code: "US", name: "United States", dialCode: "1", flag: "🇺🇸" },
];